# libs
libs = ['download_lib.py', 'downloadFiles_lib.py', 'fileMan_lib', 'characterSet_lib.py', 'characterUI_macro_lib.py',
        'constraint_lib.py', 'constraintUI_macro_lib.py', 'constraintUI_micro_lib.py', 'display_lib.py',
        'key_anim_lib.py', 'lists_lib.py', 'selection.py', 'selectionSet_lib.py',
        'selectionUI_macro_lib.py', 'zero.py', 'autoTangent.mel', 'pairSelect.py',
        'animCurve_lib.py', 'animCopyPaste_lib.py', 'animation_library_manager.py',
        'anim_lib.py', 'ui_micro_lib.py', 'sys_lib.py', 'playblast_lib.py', 'togglePlate.py',
        'graphFilter.py', 'curveSoftSelect.py', 'pairSelectList.txt', 'animRig_lib.py', 'clipPickle_lib.py',
        'clipPickleUI_micro_lib.py', 'clipPickleUI_macro_lib.py']

# icons Anim Shelf
icons = [
    'animIn.png',
    'animOut.png',
    'animUI.png',
    'Atom.png',
    'blast.png',
    'blastUI.png',
    'csAdd.png',
    'csEx.png',
    'csIm.png',
    'csMbrTgl.png',
    'csMinus.png',
    'ctrMinus.png',
    'ctrPlus.png',
    'distance.png',
    'flush.png',
    'flushUn.png',
    'followCam.png',
    'frustum.png',
    'geBttns.png',
    'guides.png',
    'helpersUI.png',
    'kmh.png',
    'matchKeys.png',
    'matchAll.png',
    'plateRange.png',
    'plateToggle.png',
    'projectSet.png',
    'quickUndo.png',
    'reloadShelf.png',
    'savePlus.png',
    'sel.png',
    'selMrrOff.png',
    'selMrrOn.png',
    'selPrint.png',
    'selSet.png',
    'selSetUI.png',
    'selStore.png',
    'toggleUI.png',
    'warpTimeUI.png'
    ]

# icons Rigging Shelf
iconsRig = ['refreshWeb.png', 'save++_icon.png', 'PrjtSet.xpm', 'sel.xpm', 'selStore.xpm', 'saveFileUI.xpm', 'Atom.png', 'AtmWghtUtl.xpm', 'AtomUtl.xpm',
            'AtmTrnsfrInflnc.xpm', 'AtmSrfcRg.xpm', 'AtomLck.xpm', 'AtmMshUpdt.xpm', 'TagUI.xpm', 'Zero.xpm', 'PrntSel.png']
